controller_list:
  - name: fake_left_arm_controller
    joints:
      - $(arg left_prefix)joint_1
      - $(arg left_prefix)joint_2
      - $(arg left_prefix)joint_3
      - $(arg left_prefix)joint_4
      - $(arg left_prefix)joint_5
      - $(arg left_prefix)joint_6
      - $(arg left_prefix)joint_7
  - name: fake_right_arm_controller
    joints:
      - $(arg right_prefix)joint_1
      - $(arg right_prefix)joint_2
      - $(arg right_prefix)joint_3
      - $(arg right_prefix)joint_4
      - $(arg right_prefix)joint_5
      - $(arg right_prefix)joint_6
      - $(arg right_prefix)joint_7
  - name: fake_left_gripper_controller
    joints:
      - $(arg left_prefix)finger_joint
  - name: fake_right_gripper_controller
    joints:
      - $(arg right_prefix)finger_joint
initial:  # Define initial robot poses.
  - group: left_arm
    pose: left_arm_home
  - group: right_arm
    pose: right_arm_home
  - group: left_gripper
    pose: left_gripper_close
  - group: right_gripper
    pose: right_gripper_close