# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: 
    - left_arm 
    - rihgt_arm
  joint_model_group_pose: 
    - left_arm_home 
    - right_arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - $(arg prefix)l_wheel_joint
    - $(arg prefix)r_wheel_joint
    - $(arg left_prefix)joint_1
    - $(arg left_prefix)joint_2
    - $(arg left_prefix)joint_3
    - $(arg left_prefix)joint_4
    - $(arg left_prefix)joint_5
    - $(arg left_prefix)joint_6
    - $(arg left_prefix)joint_7
    - $(arg left_prefix)finger_joint
    - $(arg prefix)main_cam_yaw_joint
    - $(arg prefix)main_cam_pitch_joint
    - $(arg right_prefix)joint_1
    - $(arg right_prefix)joint_2
    - $(arg right_prefix)joint_3
    - $(arg right_prefix)joint_4
    - $(arg right_prefix)joint_5
    - $(arg right_prefix)joint_6
    - $(arg right_prefix)joint_7
    - $(arg right_prefix)finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg left_prefix)joint_1
      - $(arg left_prefix)joint_2
      - $(arg left_prefix)joint_3
      - $(arg left_prefix)joint_4
      - $(arg left_prefix)joint_5
      - $(arg left_prefix)joint_6
      - $(arg left_prefix)joint_7
  - name: right_arm_gen3_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg right_prefix)joint_1
      - $(arg right_prefix)joint_2
      - $(arg right_prefix)joint_3
      - $(arg right_prefix)joint_4
      - $(arg right_prefix)joint_5
      - $(arg right_prefix)joint_6
      - $(arg right_prefix)joint_7
  - name: left_arm_robotiq_2f_85_gripper_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - $(arg left_prefix)finger_joint
  - name: right_arm_robotiq_2f_85_gripper_controller
    action_ns: gripper_cmd
    default: True
    type: GripperCommand
    joints:
      - $(arg right_prefix)finger_joint
  